git:
  depth: false

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

script: yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: dist
  on:
    branch: master
  target-branch: gh-pages

sudo: false
