git:
  depth: false

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - mv travis.config.js vue.config.js
  - yarn run build
  - cp -r public/mock/logout dist/mock # dang it webpack
  - cp public/landing/index.html dist/landing

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: dist
  on:
    branch: master
  target-branch: gh-pages

sudo: false
